### ISSUE TITLE
Add filtering/sorting for all data feeds

### ISSUE THREAD

**Issue by bradbarkhouse** [bradbarkhouse/mysportsfeeds-api#29]
Currently data feeds return a huge amount of data for all relevant players/teams/games.

We'll be adding additional filters and sorting for each feed.  The type of filters and sorting will be specific to each feed.

**Comment by bradbarkhouse** [comment]
We've split this into two phases: 1) Filtering and 2) Sorting

The Filtering phase is now completed!  You can check out all the new params for each feed in the API docs at https://www.mysportsfeeds.com/data-feeds/api-docs/.

**Comment by mkove** [comment]
Per our conversation on Slack.  

- Add a parameter to MLB Cumulative Player Stats Feed - Qualifier
- this parameter determines if a player qualifies for consideration for League Leaders
- it is defined on the footer of this page: http://mlb.mlb.com/stats/sortable.jsp This page also has a "toggle" button to view all players, and Qualified players.  this is what is attempted to be replicated
- Official definition: A batter must have 3.1 plate appearances per team game played (1.86 PA during spring training) to qualify for league leadership in AVG, OBP or SLG; a pitcher must have 1.0 innings pitched per team game (0.6 IP during spring training) to qualify for league leadership in ERA."
- They key variable for determining qualified is # of games played total by the player. "per team game"

**Comment by bradbarkhouse** [comment]
Sorting functionality is now completed and API Docs have been updated!

@mkove a new `qualified` param has been added to the **cumulative_player_stats** and **daily_player_stats** feeds which, when set to "true", will only include results for qualified games.  (Works for MLB only right now)

**Comment by mkove** [comment]
Excellent, thanks, I'll check it out later today!  This is only applicable to MLB, I'm not sure of if the other sports have similar formulas, but If I find out, I'll let you know.

**Comment by mkove** [comment]
@bradbarkhouse I'm looking for  the qualified param in the cumulative_player_stats for 2018 season, and cannot find it, has it been removed?

**Comment by bradbarkhouse** [comment]
@mkove it's still there, I think maybe it was mistakenly omitted from the latest iteration of the API Docs.

**Comment by mkove** [comment]
@bradbarkhouse From visual inspection, I'm not 100% sure this is working correctly, the results do not appear to match what the official "Qualified" stats show.  Also, isince it is not showing in the feed (the qualified field), we my developers are telling me we can't filter on it.

To simplify this, and move this onto our agenda, we can write our own formula, but we are missing one field of information on these feeds (cumulative_player_stats and daily_player_stats).  Would it be possible to add a field to the results, in the team section, called "Team Games Played".  We have the rest of the data we need to calculate the formula ourselves .

For example, something like this

team":{"ID":"130","City":"Atlanta","Name":"Braves","Abbreviation":"ATL","TeamGP":"71"}

**Comment by mkove** [comment]
NOTE: I Posted this on Slack, but am posting it here to keep a record....

Ok, here comes a long detailed explanation that I hope makes this clearer, and will allow us to come to resolution quicker.  To accommodate for the best user experience, we pull all of the stats, and then filter them accordingly on our end, by storing in cache on server and on local users machine, that way when a user wants to switch from regular stats to qualified stats, a filter is applied, at the presentation layer, what we have already downloaded.  With the way that you have set is a parameter, there is no qualified param, for each player, in the feed.  So, our users would have to re-download the stats to switch from qualified to non-qualified.  Since there is also a different formula for pitching, this presents a situation where the user would need to download the data 4 times to see qualified batting and pitching stats.   Lastly, the formula is a bit complicated, and I don't believe it is being applied correctly, and I illustrate an example later.  If we calculate it on our end, that would be best for ensuring we get it right, and take it off of your end.  The formula is actually based on Team Games Played, NOT Player Games Played.  the data in the feed contains the amount of games a player has played.  What is needed to determine if a player qualifies, according to the formula, is the amount of games played by the team to date for the current season.  So a Player may have played in 40 games, but his team has played 71 games to date.  that is why on github I suggested to include the TeamGP stat in the team portion of the individual player stats.    Even if it was efficient for us to download the stats twice (regular and ?qualified=true)  I don't believe the formula for ?qualified=true is being currently calculated correctly on your end.    As an example, in this feed  https://api.mysportsfeeds.com/v1.2/pull/mlb/2018-regular/cumulative_player_stats.json?qualified=true This player shouldn't be listed. "ID":"10387","LastName":"Naquin","FirstName":"Tyler"   While he has played 37 games (GamesPlayed) that doesn't really factor into the formula.  The formula is based upon the amount of games the Cleveland Indians have played.  To date they have played 76 games.  That is the number that is needed for the formula.  While it is possible for us to pull that number from another feed, that becomes extra overhead and more programming and difficult to execute, I'm being told.  Ideally, if a new number, TeamGP is displayed, for each Player, than we can do the calculation we need without an abundance of work, and we can then perform the calculation ourselves without having to ask you to troubleshoot any further.  I hope that's clear, if not, let me know.

**Comment by mkove** [comment]
To illustrate what we need to do, if you go to this page, you will see a button that toggles between "All Players | Qualifiers" http://cleveland.indians.mlb.com/stats/sortable.jsp?c_id=cle#elem=%5Bobject+Object%5D&tab_level=child&click_text=Sortable+Player+hitting&game_type='R'&season=2018&season_type=ANY&league_code='MLB'&sectionType=sp&statType=hitting&page=1&ts=1529927243838&playerType=QUALIFIER

As an alternative, we could troubleshoot the formula, and get that correct, and then for each player, include the data that says true or false for each player, however, we would need to do this differently based upon pitching or batting statistics.  Also, there is a similar stat that is needed for NHL, so I think the TeamGP stat would be better.  As you can see here, all of the formulas are based upon Team games played (or they call it Scheduled games played - same thing) https://www.hockey-reference.com/about/rate_stat_req.html
