### ISSUE TITLE
v2.0 games feeds are extremely slow

### ISSUE THREAD

**Issue by thegreatco** [bradbarkhouse/mysportsfeeds-api#88]
I'm trying to pull some of the MLB daily games lists and it seems past days pull just fine, but future games are either taking a _very_ long time, or are block loading completely. I haven't received any errors (connection resets, 404's, 500's, etc) yet.

The latest url I've tried is
```
https://api.mysportsfeeds.com/v2.0/pull/mlb/2018-regular/date/20180718/games.json
```
Perhaps it is transient, perhaps no, I will try later.

Thanks for all the great work so far on this new API, it's looking great!

**Comment by thegreatco** [comment]
Quick update, chrome reports the request finished successfully after 2 minutes (exactly) with no games reported. For that particular date, that is correct, there are no games, but it took a very long time to get that result.

**Comment by bradbarkhouse** [comment]
@thegreatco we've identified some inefficiency with the games feeds, due to the fact that they're combining schedule and score data.  So it's slow for the first request until the underlying dataset is generated.  But still, for a date with no games, I would have expected a faster response.  We have a solution in mind, we'll get that released soon.

**Comment by thegreatco** [comment]
👍 just wanted to give you guys a heads up. As always, thanks for the quick response.

**Comment by bradbarkhouse** [comment]
This has now been addressed @thegreatco , particularly for days where there are no games scheduled, or only completed games.  Let me know if you're still seeing problems and we'll re-open.
